import { test } from 'node:test';
import assert from 'node:assert';
import fs from 'fs';
import path from 'path';

// These tests validate the on-disk reviews index. Generated by
// scripts/generate-index.ts from the markdown files under data/reviews/.
// Failing means generate-index needs to be re-run (and possibly
// apply-tags + the source markdown updated) before merging.

const INDEX_PATH = path.join(process.cwd(), 'data/reviews-index.json');

interface IndexedReview {
  slug: string;
  contestId: string;
  title: string;
  tags?: string[];
}

let cachedReviews: IndexedReview[] | null = null;
function loadReviews(): IndexedReview[] {
  if (cachedReviews) return cachedReviews;
  cachedReviews = JSON.parse(fs.readFileSync(INDEX_PATH, 'utf8'));
  return cachedReviews!;
}

test('reviews-index.json exists', () => {
  assert.ok(fs.existsSync(INDEX_PATH), `${INDEX_PATH} not found — run pnpm generate-index`);
});

test('every review has at least one tag', () => {
  const reviews = loadReviews();
  const untagged = reviews.filter(r => !r.tags || r.tags.length === 0);
  if (untagged.length > 0) {
    const sample = untagged.slice(0, 10).map(r => `${r.contestId}/${r.slug}`).join('\n  ');
    assert.fail(
      `${untagged.length} review(s) have no tags. The home-page tag filter ` +
      `can't surface untagged reviews.\nFirst few:\n  ${sample}\n\n` +
      `Fix: add entries to data/review-tags.json and run ` +
      `npx tsx scripts/apply-tags.ts && pnpm generate-index.`
    );
  }
});
